### PR TITLE
Adding a "light theme"

### PR DESCRIPTION
**Pull request by aaronsarnat**
image

Should look good with AllenNLP demo integration.

To use it, just add `hierplane--theme-light` class to the div that has the `hierplane` class:

```
<div className="hierplane hierplane--theme-light">
```

### CODE REVIEW

**Comment by aaronsarnat** [comment]
@codeviking FYI. If you want to add this as a custom feature to AllenNLP but not Hierplane core, that's fine with me. There's a lot of CSS involved in overriding the base styles, so we may not want to add the additional weight to the core. Then again, maybe we do. Maybe there's a compelling reason to give users the option to choose between a default (dark) and a light.

In any case, there's undoubtedly a more elegant way to do theming, but seems like it would require some re-architecting (which we may want to do at some point anyway)...

**Review by codeviking — CHANGES_REQUESTED** [review]
Sweet! Can you add a property that enables this.  Likely something like `inverse={true}` or `theme="light"` on the top-level tree component?

Once that's in, this is g2g.

Also, can you add a TODO that notes that ideally we wouldn't include all themes in the every CSS bundle, and instead we'd produce separate CSS files that the end user could include as appropriate?  That way they'd get smaller static files.

**Comment by aaronsarnat** [comment]
@codeviking PTAL.

Adding `theme="light"` to the top-level component ought to do it.

[edit]
Just added the requested TODO comment and a trailing newline on the theme file.
[/edit]

**Review by codeviking — CHANGES_REQUESTED** [review]
We should add to to `src/static/hierplane.js` as well, so that it's accessible to users who are nesting it into a webpage that doesn't include React.  Let's add it as a supported option.

LMK if that's not clear.

**Comment by aaronsarnat** [comment]
@codeviking I made the requested change to `hierplane.js` and explained the option in the README. PTAL.

**Review by codeviking — APPROVED** [review]
Great -- ship it!

**Pull request merged**
